general:
  modality: monuseg  
  corr_mode: diffusion_ls # diffusion on level sets
  img_cond: 1 # condition on image to obtain segmentation mask
  data_path: "/home/lea/Data/MonuSeg_spcn_trunc"
  csv_train: "train.csv"
  csv_test: "test.csv"
  batch_size: 32
  sz: 128 # 128, 256
  resume_training: False
  load_path: ''
  class_label_cond: False 
  num_classes: 0
  with_class_label_emb: False

inference:
  latest: False
  load_exp: ''
  n_samples: 4

model:
  type: 'unet' 
  n_cin: 1 # 1, n_classes
  n_cin_cond: 1 # 1, 3 for gray/color valued input
  n_fm: 10 
  dim: 128
  embedding: 'sinusoidal'
  mults:
   - 1
   - 2
   - 4
   - 4

learning:
  epochs: 500000
  lr: 1.0E-4
  loss: 2 
  n_val: 8
  clip: 40000. 
  gpus:
    - 1

SMLD:
  sde: 'vp' # VE used in GCPR paper, VP scheme is like classic DDPM
  beta_1: 1.E-4 # default from DDPM
  beta_T: 0.02 # default from DDPM
  T: 1000 # default from DDPM
  n_steps: 100 # VE params
  sigma_1_m: 5. # VE params: heuristic
  sigma_L_m: 0.001 # VE params: heuristic
  objective: 'cont'
  sampler: 'pc' # for VE scheme with reverse SDE
  eps: 2.0E-5 # annealed Langevin 
  N: 200 # Predictor steps
  M: 1 # Corrector steps
  r: 0.15 # "snr" for PC sampling
